### ISSUE TITLE
MEETING ON SATURDAY

### ISSUE THREAD

**Issue by kajayr** [jpmarinacci/capstone#55]
In order to warp up the project for this quarter, because we had a lack of quantity of members in the last meeting, it's mandatory to join to this meeting on this Saturday 3/14. We expect everyone to show up. Please review the tasks so we can move the process when we meet. We are going to stay in the meeting for a long time, so please don't make a plan for this specific day. 

Meeting starts at 5 and the lab is open till mid-night

**Comment by ArenKasner** [comment]
I will be there

**Comment by Tgylove** [comment]
I will be there 

thanks

**Comment by swrocks** [comment]
Could we move the meeting earlier? Like start at noon or early afternoon(1 PM?), and spend the whole afternoon together. It is difficult for me to stay at evening or night with the team, especially on the weekend. Thank you for your understanding!

**Comment by kajayr** [comment]
Sunny the project is almost over but we are missing your part. JP is free the whole day, so he can come at noon and you join him and work together as much as possible, the team will join at 5. I know Aren is working, but Belete, if you can, please join erlier.

**Comment by kajayr** [comment]
Team, please let me know what time is the best on Wednesday to meet up with Sapan and Maricel. 
All Information I have for now is...
Aren will be free afternoon
I need others information too so I can make a schedule as soon as possible.

**Comment by swrocks** [comment]
I and JP is here from 1PM, you guys can join anytime.

Just be aware that the N building is closing today at 6PM.

**Comment by kajayr** [comment]
I will be there after work at 4:30
