### ISSUE TITLE
add opportunity model/table fields to specs

### ISSUE THREAD

**Issue by jpmarinacci** [jpmarinacci/capstone#66]
open the WhiteBoard-04242018.jpg  picture from the google drive specs folder
- [x]  create a text file document or word doc (preferraly .txt)
- [x] copy each field from image to the file

- [x] save the file in the capstone\documentation\specs folder

- [x] commit the file to the git repository 
 (git add filename, git commit -m "specs folder updated", git push)

**Comment by kajayr** [comment]
Done
